// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgo94NmLf_zVR6kBI5be-19anmV8L8v2k',
    appId: '1:744758112717:web:975125911cfe2c2a339484',
    messagingSenderId: '744758112717',
    projectId: 'tokentosha',
    authDomain: 'tokentosha.firebaseapp.com',
    storageBucket: 'tokentosha.firebasestorage.app',
    measurementId: 'G-H28LP8LY1D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnpLiaFPzhtFoXb8FlvdDrYyJ_lFWtfRE',
    appId: '1:744758112717:ios:7a16a848e10c545e339484',
    messagingSenderId: '744758112717',
    projectId: 'tokentosha',
    storageBucket: 'tokentosha.firebasestorage.app',
    iosBundleId: 'com.example.tokentosha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnpLiaFPzhtFoXb8FlvdDrYyJ_lFWtfRE',
    appId: '1:744758112717:ios:7a16a848e10c545e339484',
    messagingSenderId: '744758112717',
    projectId: 'tokentosha',
    storageBucket: 'tokentosha.firebasestorage.app',
    iosBundleId: 'com.example.tokentosha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgo94NmLf_zVR6kBI5be-19anmV8L8v2k',
    appId: '1:744758112717:web:d89263d5dab07852339484',
    messagingSenderId: '744758112717',
    projectId: 'tokentosha',
    authDomain: 'tokentosha.firebaseapp.com',
    storageBucket: 'tokentosha.firebasestorage.app',
    measurementId: 'G-0TGGD86K7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs9GtnCboNQpbidP-vgss2rMD325A508s',
    appId: '1:744758112717:android:3d96103f300c80cd339484',
    messagingSenderId: '744758112717',
    projectId: 'tokentosha',
    storageBucket: 'tokentosha.firebasestorage.app',
  );

}